### ISSUE TITLE
settings problems

### ISSUE THREAD

**Issue by helenadm** [rinocloud/rinobot#17]
bundle.js:6 Uncaught Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bname%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

**Comment by eoinmurray** [comment]
im so happy that this is fucking fixed cos it was fucking hard to fucking fix
