### ISSUE TITLE
one folder receiving data correctly. the other getting nothing. the bot is telling me all file uploaded

### ISSUE THREAD

**Issue by finmurray** [rinocloud/rinobot#31]
hottest received correct files. bottest2 didn't receive any files (.pdfs)

![screenshot_22](https://cloud.githubusercontent.com/assets/21021447/17649327/ea324c1a-6232-11e6-9301-1290d51cd952.jpg)

**Comment by eoinmurray** [comment]
User interface issue -> it should be explained that the tasks run sequentially.
So if you reverse the task order it will work. 

Here the second task wont work, because the pdf's will have already been uploaded.

**Comment by finmurray** [comment]
Ok. Ive run *. first and then *pdf and it works. Ive also put *docx into one folder and *pdf into another without using a * setting and that works as well.

UI issue so and not a bug
