### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by helenadm** [rinocloud/rinobot#42]
pipeline >>> {    ░⸩ ⠦ runTopLevelLifecycles: sill runTopLevelLifecycles Finish
  "index": 0,
  "error": {
    "errno": -2,
    "code": "ENOENT",
    "syscall": "access",
    "path": "/Users/helenadomo/Desktop/Test/rino.yaml"
  },
  "pipePath": ".DS_Store"
}

**Comment by helenadm** [comment]
![screen shot 2016-09-18 at 16 13 53](https://cloud.githubusercontent.com/assets/17926955/18616845/0ec6fd7a-7dbb-11e6-9a2e-8057582096e8.png)

**Comment by eoinmurray** [comment]
Closed this because it was result of some bad operation.
